export default class Games {
	static GamesList = [
		// Streamed via Discord
		// Jackbox 4
		{
			"name": "Fibbage 3",
			"min_players": 2,
			"max_players": 8,
			"requires": "Jackbox 4",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/610180/The_Jackbox_Party_Pack_4/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		{
			"name": "Fibbage Enough about You",
			"min_players": 2,
			"max_players": 8,
			"requires": "Jackbox 4",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/610180/The_Jackbox_Party_Pack_4/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		{
			"name": "Survive the Internet",
			"min_players": 3,
			"max_players": 8,
			"requires": "Jackbox 4",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/610180/The_Jackbox_Party_Pack_4/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		{
			"name": "Monster Seeking Monster",
			"min_players": 3,
			"max_players": 7,
			"requires": "Jackbox 4",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/610180/The_Jackbox_Party_Pack_4/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		{
			"name": "Bracketeering",
			"min_players": 3,
			"max_players": 16,
			"requires": "Jackbox 4",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/610180/The_Jackbox_Party_Pack_4/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		{
			"name": "Civic Doodle",
			"min_players": 3,
			"max_players": 8,
			"requires": "Jackbox 4",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/610180/The_Jackbox_Party_Pack_4/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		// Jackbox 5
		{
			"name": "You dont know jack",
			"min_players": 1,
			"max_players": 8,
			"requires": "Jackbox 5",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/774461/The_Jackbox_Party_Pack_5/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		{
			"name": "Split the room",
			"min_players": 3,
			"max_players": 8,
			"requires": "Jackbox 5",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/774461/The_Jackbox_Party_Pack_5/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		{
			"name": "Mad verse city",
			"min_players": 3,
			"max_players": 8,
			"requires": "Jackbox 5",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/774461/The_Jackbox_Party_Pack_5/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		{
			"name": "Patently stupid",
			"min_players": 3,
			"max_players": 8,
			"requires": "Jackbox 5",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/774461/The_Jackbox_Party_Pack_5/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		{
			"name": "Zeeple dome",
			"min_players": 1,
			"max_players": 6,
			"requires": "Jackbox 5",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/774461/The_Jackbox_Party_Pack_5/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		// Jackbox 6
		{
			"name": "Trivia murder party 2",
			"min_players": 1,
			"max_players": 8,
			"requires": "Jackbox 6",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/1005300/The_Jackbox_Party_Pack_6/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		{
			"name": "Role models",
			"min_players": 3,
			"max_players": 6,
			"requires": "Jackbox 6",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/1005300/The_Jackbox_Party_Pack_6/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		{
			"name": "Joke boat",
			"min_players": 3,
			"max_players": 8,
			"requires": "Jackbox 6",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/1005300/The_Jackbox_Party_Pack_6/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		{
			"name": "Dictionarium",
			"min_players": 3,
			"max_players": 8,
			"requires": "Jackbox 6",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/1005300/The_Jackbox_Party_Pack_6/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		{
			"name": "Push the button",
			"min_players": 4,
			"max_players": 10,
			"requires": "Jackbox 6",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/1005300/The_Jackbox_Party_Pack_6/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		// Jackbox Party Pack 7
		{
			"name": "Quiplash 3",
			"min_players": 3,
			"max_players": 8,
			"requires": "Jackbox 7",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/1211630/The_Jackbox_Party_Pack_7/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		{
			"name": "The Devils and the Details",
			"min_players": 3,
			"max_players": 8,
			"requires": "Jackbox 7",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/1211630/The_Jackbox_Party_Pack_7/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		{
			"name": "Champ’d Up",
			"min_players": 3,
			"max_players": 8,
			"requires": "Jackbox 7",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/1211630/The_Jackbox_Party_Pack_7/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		{
			"name": "Talking Points",
			"min_players": 3,
			"max_players": 8,
			"requires": "Jackbox 7",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/1211630/The_Jackbox_Party_Pack_7/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		{
			"name": "Blather ‘Round",
			"min_players": 2,
			"max_players": 6,
			"requires": "Jackbox 7",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/1211630/The_Jackbox_Party_Pack_7/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		// Jackbox Party Pack 8
		{
			"name": "Drawful: Animate",
			"min_players": 3,
			"max_players": 10,
			"requires": "Jackbox 10",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/1552350/The_Jackbox_Party_Pack_8/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		{
			"name": "The Wheel of Enormous Proportions",
			"min_players": 2,
			"max_players": 8,
			"requires": "Jackbox 10",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/1552350/The_Jackbox_Party_Pack_8/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		{
			"name": "Job Job",
			"min_players": 3,
			"max_players": 10,
			"requires": "Jackbox 10",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/1552350/The_Jackbox_Party_Pack_8/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		{
			"name": "The Poll Mine",
			"min_players": 2,
			"max_players": 10,
			"requires": "Jackbox 10",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/1552350/The_Jackbox_Party_Pack_8/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		{
			"name": "Weapons Drawn",
			"min_players": 4,
			"max_players": 8,
			"requires": "Jackbox 10",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/1552350/The_Jackbox_Party_Pack_8/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		// Steam
		{
			"name": "Drawful 2",
			"min_players": 3,
			"max_players": 8,
			"requires": "Drawful",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/442070/Drawful_2/",
			"host_platforms": ["windows", "mac", "linux"],
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},

		// Thick client
		// Steam (Win, Mac, Lin)
		{
			"name": "Clue",
			"min_players": 3,
			"max_players": 6,
			"requires": "Tabletop Simulator",
			"requires_streaming": false,
			"url": "https://store.steampowered.com/app/286160/Tabletop_Simulator/",
			"client_platforms": ["windows", "mac", "linux"],
			"game_categories": ["board"],
		},
		{
			"name": "Deceit",
			"min_players": 6,
			"max_players": 6,
			"requires": "Deceit",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/466240/Deceit/",
			"client_platforms": ["windows"],
			"game_categories": ["videogame"],
		},
		// Steam (Win), Mobile (Android, iOS)
		{
			"name": "Among Us",
			"min_players": 4,
			"max_players": 10,
			"requires": "Among Us",
			"requires_streaming": false,
			"url": "https://store.steampowered.com/app/945360/Among_Us/",
			"client_platforms": ["windows", "android", "ios", "proton"],
			"game_categories": ["videogame"],
		},
		// Steam (Win), Mobile (Android, iOS)
		{
			"name": "Carcassone",
			"min_players": 1,
			"max_players": 6,
			"requires": "Carcassone",
			"requires_streaming": false,
			"url": "https://www.asmodee-digital.com/en/carcassonne/",
			"client_platforms": ["windows", "android", "ios"],
			"game_categories": ["board"],
		},
		// Steam (Win), Mobile (Android, iOS)
		{
			"name": "Splendor",
			"min_players": 2,
			"max_players": 4,
			"requires": "Splendor",
			"requires_streaming": false,
			"url": "https://www.asmodee-digital.com/en/splendor/",
			"client_platforms": ["windows", "android", "ios"],
			"game_categories": ["board"],
		},
		// Steam (Win)
		{
			"name": "Clue/Cluedo",
			"min_players": 2,
			"max_players": 6,
			"requires": "Clue/Cluedo",
			"requires_streaming": false,
			"url": "https://store.steampowered.com/app/794800/ClueCluedo_The_Classic_Mystery_Game/",
			"client_platforms": ["windows"],
			"game_categories": ["board"],
		},

		// Web client
		// Netgames
		{
			"name": "One Night Werewolf",
			"min_players": 3,
			"max_players": 21,
			"requires": "N/A",
			"requires_streaming": false,
			"url": "https://netgames.io/games/onu-werewolf/",
			"client_platforms": ["web"],
			"game_categories": ["board"],
		},
		{
			"name": "Codewords",
			"min_players": 4,
			"max_players": 100,
			"requires": "N/A",
			"requires_streaming": false,
			"url": "https://netgames.io/games/codewords/",
			"client_platforms": ["web"],
			"game_categories": ["board"],
		},
		{
			"name": "Spyfall",
			"min_players": 3,
			"max_players": 100,
			"requires": "N/A",
			"requires_streaming": false,
			"url": "https://netgames.io/games/spyfall/",
			"client_platforms": ["web"],
			"game_categories": ["board"],
		},
		{
			"name": "Love Letter",
			"min_players": 2,
			"max_players": 4,
			"requires": "N/A",
			"requires_streaming": false,
			"url": "https://netgames.io/games/love-letter/",
			"client_platforms": ["web"],
			"game_categories": ["board"],
		},
		{
			"name": "Avalon",
			"min_players": 5,
			"max_players": 10,
			"requires": "N/A",
			"requires_streaming": false,
			"url": "https://netgames.io/games/avalon/",
			"client_platforms": ["web"],
			"game_categories": ["board"],
		},
		{
			"name": "Enigma",
			"min_players": 4,
			"max_players": 100,
			"requires": "N/A",
			"requires_streaming": false,
			"url": "https://netgames.io/games/enigma/",
			"client_platforms": ["web"],
			"game_categories": ["board"],
		},
		// Secret Hitler
		{
			"name": "Secret Hitler",
			"min_players": 5,
			"max_players": 10,
			"requires": "N/A",
			"requires_streaming": false,
			"url": "https://secrethitler.io/",
			"client_platforms": ["web"],
			"game_categories": ["board"],
		},
		// Skribbl.io
		{
			"name": "Skribbl.io",
			"min_players": 2,
			"max_players": 10,
			"requires": "N/A",
			"requires_streaming": false,
			"url": "https://skribbl.io/",
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		// PretendYourXyzzy
		{
			"name": "Pretend you're Xyzzy / Cards Against Humanity",
			"min_players": 3,
			"max_players": 20,
			"requires": "N/A",
			"requires_streaming": false,
			"url": "https://pretendyoure.xyz/zy/",
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		// MassiveDecks
		{
			"name": "MassiveDecks / Cards Against Humanity",
			"min_players": 3,
			"max_players": 50,
			"requires": "N/A",
			"requires_streaming": false,
			"url": "https://pretendyoure.xyz/zy/",
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		// Gartic Phone
		{
			"name": "Gartic Phone / Pictionary",
			"min_players": 3,
			"max_players": 14,
			"requires": "N/A",
			"requires_streaming": false,
			"url": "https://garticphone.com/",
			"client_platforms": ["web"],
			"game_categories": ["party"],
		},
		// BoardGamesArena, selected games
		{
			"name": "Solo",
			"min_players": 2,
			"max_players": 10,
			"requires": "BoardGameArena Subscription",
			"requires_streaming": false,
			"url": "https://boardgamearena.com/gamepanel?game=solo",
			"client_platforms": ["web"],
			"game_categories": ["cards"],
		},
		{
			"name": "Coup",
			"min_players": 2,
			"max_players": 8,
			"requires": "BoardGameArena Subscription",
			"requires_streaming": false,
			"url": "https://boardgamearena.com/gamepanel?game=coupcitystate",
			"client_platforms": ["web"],
			"game_categories": ["board"],
		},
		{
			"name": "Love Letter",
			"min_players": 3,
			"max_players": 8,
			"requires": "BoardGameArena Subscription",
			"requires_streaming": false,
			"url": "https://boardgamearena.com/gamepanel?game=loveletter",
			"client_platforms": ["web"],
			"game_categories": ["board"],
		},
		{
			"name": "Carcassone",
			"min_players": 2,
			"max_players": 5,
			"requires": "BoardGameArena Subscription",
			"requires_streaming": false,
			"url": "https://boardgamearena.com/gamepanel?game=carcassonne",
			"client_platforms": ["web"],
			"game_categories": ["board"],
		},
		{
			"name": "Settlers of Catan (Colonist)",
			"min_players": 2,
			"max_players": 4,
			"requires": "N/A",
			"requires_streaming": false,
			"url": "https://colonist.io/",
			"client_platforms": ["web"],
			"game_categories": ["board"],
		},
		{
			"name": "Settlers of Catan (Colonist)",
			"min_players": 5,
			"max_players": 6,
			"requires": "5-6 Player Game Mode Purchase",
			"requires_streaming": false,
			"url": "https://colonist.io/",
			"client_platforms": ["web"],
			"game_categories": ["board"],
		},
		{
			"name": "Settlers of Catan (Colonist)",
			"min_players": 7,
			"max_players": 8,
			"requires": "7-8 Game Mode Purchase",
			"requires_streaming": false,
			"url": "https://colonist.io/",
			"client_platforms": ["web"],
			"game_categories": ["board"],
		},

		// VIDEOGAMES
		{
			"name": "Counter-Strike: Global Offensive",
			"min_players": 2,
			"max_players": 32,
			"requires": "N/A",
			"requires_streaming": false,
			"url": "https://store.steampowered.com/app/730/CounterStrike_Global_Offensive/",
			"host_platform": ["windows", "linux"],
			"client_platforms": ["windows", "mac", "linux"],
			"game_categories": ["videogame"],
		},
	]
}

