export default class Games {
	static GamesList = [
		// Streamed via Discord
		// Jackbox 4
		{
			"name": "Fibbage 3",
			"min_players": 2,
			"max_players": 8,
			"requires": "Jackbox 4",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/610180/The_Jackbox_Party_Pack_4/",
		},
		{
			"name": "Fibbage Enough about You",
			"min_players": 2,
			"max_players": 8,
			"requires": "Jackbox 4",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/610180/The_Jackbox_Party_Pack_4/",
		},
		{
			"name": "Survive the Internet",
			"min_players": 3,
			"max_players": 8,
			"requires": "Jackbox 4",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/610180/The_Jackbox_Party_Pack_4/",
		},
		{
			"name": "Monster Seeking Monster",
			"min_players": 3,
			"max_players": 7,
			"requires": "Jackbox 4",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/610180/The_Jackbox_Party_Pack_4/",
		},
		{
			"name": "Bracketeering",
			"min_players": 3,
			"max_players": 16,
			"requires": "Jackbox 4",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/610180/The_Jackbox_Party_Pack_4/",
		},
		{
			"name": "Civic Doodle",
			"min_players": 3,
			"max_players": 8,
			"requires": "Jackbox 4",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/610180/The_Jackbox_Party_Pack_4/",
		},
		// Jackbox 5
		{
			"name": "You dont know jack",
			"min_players": 1,
			"max_players": 8,
			"requires": "Jackbox 5",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/774461/The_Jackbox_Party_Pack_5/",
		},
		{
			"name": "Split the room",
			"min_players": 3,
			"max_players": 8,
			"requires": "Jackbox 5",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/774461/The_Jackbox_Party_Pack_5/",
		},
		{
			"name": "Mad verse city",
			"min_players": 3,
			"max_players": 8,
			"requires": "Jackbox 5",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/774461/The_Jackbox_Party_Pack_5/",
		},
		{
			"name": "Patently stupid",
			"min_players": 3,
			"max_players": 8,
			"requires": "Jackbox 5",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/774461/The_Jackbox_Party_Pack_5/",
		},
		{
			"name": "Zeeple dome",
			"min_players": 1,
			"max_players": 6,
			"requires": "Jackbox 5",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/774461/The_Jackbox_Party_Pack_5/",
		},
		// Jackbox 6
		{
			"name": "Trivia murder party 2",
			"min_players": 1,
			"max_players": 8,
			"requires": "Jackbox 6",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/1005300/The_Jackbox_Party_Pack_6/",
		},
		{
			"name": "Role models",
			"min_players": 3,
			"max_players": 6,
			"requires": "Jackbox 6",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/1005300/The_Jackbox_Party_Pack_6/",
		},
		{
			"name": "Joke boat",
			"min_players": 3,
			"max_players": 8,
			"requires": "Jackbox 6",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/1005300/The_Jackbox_Party_Pack_6/",
		},
		{
			"name": "Dictionarium",
			"min_players": 3,
			"max_players": 8,
			"requires": "Jackbox 6",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/1005300/The_Jackbox_Party_Pack_6/",
		},
		{
			"name": "Push the button",
			"min_players": 4,
			"max_players": 10,
			"requires": "Jackbox 6",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/1005300/The_Jackbox_Party_Pack_6/",
		},
		// Steam
		{
			"name": "Drawful 2",
			"min_players": 3,
			"max_players": 8,
			"requires": "Drawful",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/442070/Drawful_2/",
		},

		// Thick client
		// Steam (Win, Mac, Lin)
		{
			"name": "Clue",
			"min_players": 3,
			"max_players": 6,
			"requires": "Tabletop Simulator",
			"requires_streaming": false,
			"url": "https://store.steampowered.com/app/286160/Tabletop_Simulator/",
		},
		{
			"name": "Deceit",
			"min_players": 6,
			"max_players": 6,
			"requires": "Deceit",
			"requires_streaming": true,
			"url": "https://store.steampowered.com/app/466240/Deceit/",
		},
		// Steam (Win), Mobile (Android, iOS)
		{
			"name": "Among Us",
			"min_players": 4,
			"max_players": 10,
			"requires": "Among Us",
			"requires_streaming": false,
			"url": "https://store.steampowered.com/app/945360/Among_Us/",
		},

		// Web client
		// Netgames
		{
			"name": "One Night Werewolf",
			"min_players": 3,
			"max_players": 21,
			"requires": "N/A",
			"requires_streaming": false,
			"url": "https://netgames.io/games/onu-werewolf/",
		},
		{
			"name": "Codewords",
			"min_players": 4,
			"max_players": 100,
			"requires": "N/A",
			"requires_streaming": false,
			"url": "https://netgames.io/games/codewords/",
		},
		{
			"name": "Spyfall",
			"min_players": 3,
			"max_players": 100,
			"requires": "N/A",
			"requires_streaming": false,
			"url": "https://netgames.io/games/spyfall/",
		},
		{
			"name": "Love Letter",
			"min_players": 2,
			"max_players": 4,
			"requires": "N/A",
			"requires_streaming": false,
			"url": "https://netgames.io/games/love-letter/",
		},
		{
			"name": "Avalon",
			"min_players": 5,
			"max_players": 10,
			"requires": "N/A",
			"requires_streaming": false,
			"url": "https://netgames.io/games/avalon/",
		},
		{
			"name": "Enigma",
			"min_players": 4,
			"max_players": 100,
			"requires": "N/A",
			"requires_streaming": false,
			"url": "https://netgames.io/games/enigma/",
		},
		// Secret Hitler
		{
			"name": "Secret Hitler",
			"min_players": 5,
			"max_players": 10,
			"requires": "N/A",
			"requires_streaming": false,
			"url": "https://github.com/cozuya/secret-hitler",
		},

	]
}

